quotes_site/quotes/urls.py
from django.urls import path, include

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.index, name='main'),  # quotes:main
    path('page/<int:page>', views.index, name='main_paginate'),
    path('author/<str:aut_name>', views.author, name='author'),
    path('tag/<str:tag_name>/', views.tag, name='tag'),
    path('tag/<str:tag_name>/page/<int:page>', views.tag, name='tag_paginate'),
    path('quote/add', views.add_quote, name='add_quote'),
    path('quote/remove/<int:qt_id>', views.del_quote, name='del_quote'),
    path('quote/rescrape', views.re_scrape, name='re_scrape'),
    path('add_author', views.add_author, name='add_author'),
    path('remove_author/<int:au_id>', views.del_author, name='del_author'),
    ]

quotes_site/quotes_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('quotes.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

quotes_site/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

# from .forms import LogingForm
from .forms import LoginForm
from .views import RegisterView

app_name = 'users'


urlpatterns = [
    path('registration/', RegisterView.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html', ), name='logout'),
]

quotes_site/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    class Meta:
        db_table = 'authors'


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    class Meta:
        db_table = 'tags'


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag, db_table='quote_tag_association')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)

    class Meta:
        db_table = 'quotes'

quotes_site/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, SelectMultiple, Textarea, ValidationError
from .models import Author, Quote, Tag
from django.shortcuts import redirect, reverse


class QuoteForm(ModelForm):
    author = CharField(min_length=5, max_length=150, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    quote = CharField(min_length=5, required=True, widget=Textarea(attrs={'class': 'form-control'}))
    tags = CharField(required=False, widget=TextInput(attrs={'class': 'form-control'}))

    def clean_author(self):
        author_name = self.cleaned_data.get('author')
        if not Author.objects.filter(fullname=author_name).exists():
            raise ValidationError("This author does not exist in the database. Create the author first!")

        return Author.objects.get(fullname=author_name)

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        if tags:
            tags_list = [tag.strip() for tag in tags.split(',')]
            return tags_list
        return ''

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=40, min_length=5, widget=TextInput(attrs={'class': 'form-control'}))
    born_date = CharField(max_length=25, min_length=12, widget=TextInput(attrs={'class': 'form-control'}))
    born_location = CharField(max_length=150, min_length=12, widget=TextInput(attrs={'class': 'form-control'}))
    description = CharField(widget=Textarea(attrs={'class': 'form-control', 'size': 50}))

    def clean_fullname(self):
        fullname = self.cleaned_data.get('fullname')
        if Author.objects.filter(fullname=fullname).exists():
            raise ValidationError("This author already exists in the database")
        return fullname

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes_site/quotes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Count

from pathlib import Path
from django.conf import settings

import subprocess
from .models import Author, Quote, Tag
from .forms import AuthorForm, QuoteForm


base_dir = settings.BASE_DIR


def find_top_ten_tags():
    result_list = []
    top_ten_tags_obj = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    for tag_obj in top_ten_tags_obj:
        result_list.append(tag_obj.name)
    return result_list
# Create your views here.


def index(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_ten_tags = find_top_ten_tags()
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, "top_ten_tags": top_ten_tags})


def author(request, aut_name):
    author_details = Author.objects.get(fullname=aut_name)
    return render(request, 'quotes/author.html', context={'author': author_details})


def tag(request, tag_name, page=1):
    tag_id=Tag.objects.get(name=tag_name)
    quotes = Quote.objects.filter(tags=tag_id)
    per_page = 5
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_ten_tags = find_top_ten_tags()
    return render(request, 'quotes/tag.html', context={'quotes': quotes_on_page, "top_ten_tags": top_ten_tags,
                                                       "tag": tag_name})


@login_required
def add_quote(request):
    form = QuoteForm(instance=Quote())
    if request.method == "POST":
        form = QuoteForm(request.POST, instance=Quote())
        if form.is_valid():
            quote = form.save(commit=False)
            quote.quote = form.cleaned_data.get('quote')
            tags = form.cleaned_data.get('tags')
            quote.author = form.cleaned_data.get('author')
            if not Author.objects.filter(fullname=quote.author.fullname).exists:
                return redirect(to='quotes:add_author', context={'title': 'add new author!',
                                                                 'author': quote.author.fullname})
            quote.save()
            for tag_name in tags:
                tag, created = Tag.objects.get_or_create(name=tag_name)

                if created:
                    tag.save()
                quote.tags.add(tag)

            # Зберегти зміни в зв'язку з тегами
            quote.save()
            return redirect(to='quotes:main')

    return render(request, 'quotes/add_quote.html', context={'title': 'Add Quote', 'form': form})


@login_required
def del_quote(request, qt_id):
    quote = Quote.objects.filter(pk=qt_id)
    quote.delete()
    messages.error(request, 'quote was deleted')
    return redirect(to="quotes:main")


@login_required
def add_author(request):
    form = AuthorForm(instance=Author())
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            author = form.save(commit=False)
            author.fullname = form.cleaned_data.get('fullname')
            author.born_date = form.cleaned_data.get('born_date')
            author.born_location = form.cleaned_data.get('born_location')
            author.save()
            return redirect(to='quotes:main')
    return render(request, 'quotes/add_author.html', context={'title': 'Add Author', 'form': form})


@login_required
def del_author(request, au_id):
    author = Author.objects.get(pk=au_id)
    name = author.fullname
    quotes = Quote.objects.filter(author__fullname=author.fullname)
    for quote in quotes:
        quote.delete()

    author.delete()

    messages.error(request, f'Author {name} and all his quotes were deleted')
    return redirect(to="quotes:main")


def re_scrape(request):
    scrapy_quotes = Path(base_dir).parent / 'utils' / 'scrapy_quotes.py'
    json2mongodb = Path(base_dir).parent / 'utils' / 'json2mongodb.py'
    mongo2postgres = Path(base_dir).parent / 'utils'/ 'mongo2postgres.py'
    try:
        subprocess.run(['python', scrapy_quotes], shell=True)
        subprocess.run(['python', json2mongodb], shell=True)
        subprocess.run(['python', mongo2postgres], shell=True)

    except Exception as err:
        messages.error(request, f'quotes.toscrape.com was not re-scraped! {err}')

    messages.success(request, 'quotes.toscrape.com was re-scraped succesfully')

    return redirect(to="quotes:main")

quotes_site/quotes/templates/quotes/add_author.html
{%extends 'quotes/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h3>Add New Author</h3>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'quotes:add_author' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-3">
          <label class="form-label">Author name
          {{ form.fullname }}
          </label>
          <span>{{form.errors.fullname}}</span>
        </div>
        <div class="mt-3">
          <label  class="form-label">Born date
          {{ form.born_date }}
          </label>
          <span>{{form.errors.born_date}}</span>
        </div>
         <div class="mt-3">
          <label  class="form-label">Born location
          {{ form.born_location }}
          </label>
          <span>{{form.errors.born_location}}</span>
        </div>
        <div class="mt-3">
          <label  class="form-label">Biography
          {{ form.description }}
          </label>
          <span>{{form.errors.description}}</span>
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>
{% endblock %}

quotes_site/quotes/templates/quotes/add_quote.html
{%extends 'quotes/base.html' %}

{% block content %}

 <div class="container mt-3">
    <h1>Add New quote</h1>
    {%if form.errors and form.non_field_errors %}
    <span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
    {% endif %}
    <form action="{% url 'quotes:add_quote' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label">Author name
          {{ form.author }}
          </label>
          <span>{{form.errors.author}}</span>
        </div>
        <div class="mb-3">
          <label  class="form-label">Quote
          {{ form.quote }}
          </label>
          <span>{{form.errors.quote}}</span>
        </div>
        <div class="mb-3">
          <label  class="form-label">Tags (separate by comma)
          {{ form.tags }}
          </label>
          <span>{{form.errors.tags}}</span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Send</button>
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </form>
 </div>
{% endblock %}

quotes_site/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container">
    <div class="author-details">
        <h3 class="author-title">{{author.fullname}}</h3>
        {% if user.is_authenticated %}
            <div class="mb-3">
                <a href="{% url 'quotes:del_author' author.id %}" class="btn btn-danger">Delete Author</a>
            </div>
        {% endif %}
        <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">
            {{author.description}}
        </div>
    </div>
</div>
{% endblock %}

quotes_site/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href = {% static 'quotes/style.css' %}>
    <title>Quotes</title>
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-7">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes site</a>
                </h1>
            </div>
            <div class="col-md-5">
                <p>
                    {% if not user.is_authenticated %}
                    <a href="/users/registration">Register</a>
                    <a href="/users/login">Login</a>
                    {% else %}
                    <a href="/add_author">Add Author</a>
                    <a href="/quote/add">Add Quote</a>
                    <a href="/quote/rescrape">Re-Scrape Quotes</a>
                    <a href="/users/logout">Logout</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    {% block content %} {% endblock %}
    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes from: <a href="http://quotes.toscrape.com">Quotes.Toscrape.com</a>
            </p>
            <p class="copyright">
                Copied with <span class="zyte">❤</span> by Anton Petrenko
            </p>
        </div>
    </footer>

</body>
</html>

quotes_site/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="/author/{{quote.author.fullname}}">(about)</a>
            </span>
            {% if user.is_authenticated %}
                <div class="mb-3">
                    <a href="{% url 'quotes:del_quote' quote.id %}" class="btn btn-danger">Delete Quote</a>
                </div>
            {% endif %}
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="">
            {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}


        </div>
    </div>

    {% endfor %}

    <nav class="sticky-bottom">
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'quotes:main_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>

            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'quotes:main_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span>
                </a>
            </li>

        </ul>
    </nav>
    </div>
    <!-- top tags block -->

    <div class="col-md-4 tags-box">

            <h2>Top Ten tags</h2>
            {% for tag in top_ten_tags %}
                <span class="tag-item">
                <a class="tag-font-{{forloop.counter}}"  href="/tag/{{tag}}">{{tag}}</a>
                </span>
            {% endfor %}


    </div>

</div>

{% endblock %}

quotes_site/quotes/templates/quotes/tag.html
{% extends 'quotes/base.html' %}

{% block content %}



<div class="row">

    <div class="col-md-8">
        <h3>Viewing tag: <a href="/tag/{{tag}}">{{tag}}</a></h3>
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
            <a href="/author/{{quote.author.fullname}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="">
            {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}


        </div>
    </div>

    {% endfor %}

    <nav class="sticky-bottom">
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                    href="{% if quotes.has_previous %} {% url 'quotes:tag_paginate' tag quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>

            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'quotes:tag_paginate' tag quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span>
                </a>
            </li>

        </ul>
    </nav>
    </div>
    <!-- top tags block -->

    <div class="col-md-4 tags-box">

            <h2>Top Ten tags</h2>
            {% for tag in top_ten_tags %}
                <span class="tag-item">
                <a class="tag-font-{{forloop.counter}}"  href="/tag/{{tag}}">{{tag}}</a>
                </span>
            {% endfor %}


    </div>

</div>

{% endblock %}